<?php
// $Id: restrict_password_change.module,v 1.4 2009/08/23 03:51:31 jrglasgow Exp $
// by James Glasgow - Tribute Media - http://www.tributemedia.com

/**
 * Implementation of hook_perm()
 */
function restrict_password_change_perm() {
  return array(
    'change other users password',
    'change other users username',
    'change other users email',
    'delete other users',
    'block other users'
  );
}

/**
 * Implementation of hook_form_alter()
 */
function restrict_password_change_form_alter(&$form, $form_state, $form_id) {
  global $user;
  switch ($form_id) {
    case 'user_profile_form':
      if($user->uid != $form['_account']['#value']->uid) {
        if(!user_access('change other users password')) {
          // password cannot be changed
          $form['account']['pass']['#access'] = FALSE;
        }
        if(!user_access('change other users username')) {
          // username cannot be changed
          $form['account']['name']['#access'] = FALSE;
        }
        if(!user_access('block other users')) {
          // user cannot be blocked
          $form['account']['status']['#access'] = FALSE;
        }
        if(!user_access('change other users email')) {
          // e-mail address cannot be changed
          $form['account']['mail']['#access'] = FALSE;
        }
        if(!user_access('delete other users')) {
          // user cannot be deleted
          $form['delete']['#access'] = FALSE;
        }
      }
      // check to see if the form is for the current user or if they have permission
      // check if user 1 - if not, prevent changing user 1 account
      // regardless of permission to 'change other users password' 
      if(($user->uid != 1) && 
      ($form['_account']['#value']->uid == 1)) {
          $form['account']['#access'] = FALSE;
          $form['theme_select']['#access'] = FALSE;
          $form['contact']['#access'] = FALSE;
          $form['submit']['#access'] = FALSE;
          $form['timezone']['#access'] = FALSE;
          $form['messaging']['#access'] = FALSE;
          $form['delete']['#access'] = FALSE;
      } // protect admin usr 1
      break;
  }
}